# Generated by Django 5.0.14 on 2025-07-06 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tipoinventario',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(check=models.Q(('costo_unitario__gte', 0)), name='cost_non_negative'),
        ),
    ]
