# Generated by Django 5.0.14 on 2025-07-07 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_alter_almacen_descripcion_alter_almacen_ubicacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulo',
            name='stock_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='articulo',
            name='cost_non_negative',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario_app.tipoinventario'),
        ),
        migrations.AlterField(
            model_name='tipoinventario',
            name='cuenta_contable',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoinventario',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario_app.almacen'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario_app.almacen'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario_app.articulo'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
