# Generated by Django 5.0.14 on 2025-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0003_remove_articulo_stock_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoinventario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
