# Generated by Django 5.0.14 on 2025-08-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_alter_almacen_id_alter_articulo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='id_asiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Asiento Contable'),
        ),
    ]
